---
title: "Untitled"
author: "Jonathan Bourne"
date: "20 August 2017"
output: html_document
---



```{r}

if(file.exists(file.path(DataFolder,"LADShape.rds"))){
LADShape<- readRDS(file.path(DataFolder,"LADShape.rds"))
} else{
setwd(file.path(basewd,"ShapeFiles", "Local_Authority_Districts_December_2014_Ultra_Generalised_Clipped_Boundaries_in_Great_Britain"))

ladshape <- readOGR(dsn = list.files(pattern = "shp"))

LADShape <- fortify(ladshape, region = "objectid")

LADShape <- LADShape %>% mutate(id = as.integer(id)) %>% 
left_join(., ladshape@data, by = c("id" = "objectid")) #%>% 
#left_join(., EW2, by = c("lsoa11cd" = "ECODE"))

saveRDS(LADShape, file.path(DataFolder,"LADShape.rds"))
}


```



```{r}

LADShape <- LADShape %>%
  filter(grepl("E",lad14cd))

LADShape2 <- LADShape %>% left_join(EnglandComp, by = c("lad14cd" = "LAD11CD"))




```




```{r}
  #These two functions are necessary for Points to polygons
  get.grpPoly <- function(group,ID,df) {
    Polygon(coordinates(df[df$id==ID & df$group==group,]))
  }
  get.spPoly  <- function(ID,df) {
    Polygons(lapply(unique(df[df$id==ID,]$group),get.grpPoly,ID,df),ID)
  }
  
  #this function is necessary for the rest of the function
  points2polygons <- function(df,data) {
    spPolygons  <- SpatialPolygons(lapply(unique(df$id),get.spPoly,df))
    SpatialPolygonsDataFrame(spPolygons,match.ID=T,data=data)
  }
   
   MyData <- LADShape2 %>% #filter(AG$LAD11CD %in%  unique(dataframe$LAD11CD) ) %>%
    rename(LAD11CD = lad14cd)
  
  MyData <- SpatialPointsDataFrame(coords =MyData[,c(1,2)], data = MyData,
                                   proj4string = CRS('+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +datum=OSGB36 +units=m +no_defs'))
  MyData <- spTransform(MyData, CRS("+init=epsg:4326"))
  #random thing
  stuff <-data.frame(LAD11CD=unique(MyData$LAD11CD),row.names=unique(MyData$id))
  
  MyData<- points2polygons(MyData,stuff)
  
  #AG2 <- AG %>% group_by(LSOA_CODE) %>% summarise_all(funs(first))
  
  MyData <- EnglandComp %>%
    select(LAD11CD, Significant.Competition, LAD11NM, Comp.Type) %>%
    merge(MyData, .)
  
  class(MyData) # data.frame
  
  v<-"pk.eyJ1Ijoiam9ubm9iIiwiYSI6ImNqM2FlNXhpbDAwM3gzMW83ZW1hbHI0bzYifQ.4AfaY0Un0bKU41hZscpy9Q"
  
  m <- leaflet(MyData) %>%
    #addTiles()
    addProviderTiles("MapBox", options = providerTileOptions(
      id = "mapbox.light",
      accessToken = v))
  
  
  pal <- colorFactor("Accent", domain = MyData$Comp.Type)
  
  labels <- sprintf(
    "<strong>%s</strong><br/>Market affected %s",
    MyData$LAD11NM, MyData$Comp.Type
  ) %>% lapply(htmltools::HTML)
  
  z <-m %>% addPolygons(
    fillColor = ~pal(Comp.Type),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")
    ) %>%
    addLegend(pal = pal, values = ~Comp.Type, opacity = 0.7, title = NULL,
              position = "bottomright")
  
```



```{r}
  z
  
  mapshot(z, file = file.path(Figures, "EnglandMarket.pdf"))
```

