---
title: "NON-London"
author: "Jonathan Bourne"
date: "25 June 2017"
output: html_document
---

housing studies
internat jouranl housing policy

becky tunstall housing space inequality

niall may - between 1990 - 1995 hoomes built loads of homes built small number owned

positive money


```{r setup}
setwd( "~/Dropbox/SSE/Empty Homes/EmptyHomesCode/SubCode")
source("Setup.R")

setwd(Functions)
list.files() %>% map(source)
```



```{r}
source(file.path(CommonCode, "AuxdataLoad.R"))
```


Cumbria
```{r}
setwd(file.path(RegionsComp, "Region North West"))

BarrowCUMBRIADATA <- read_excel("Barrow-in-FurnessExemptionsLSOA.xlsx", sheet=1)[1:4]%>%  
  StructureData(.,lowuse = c(2:6,8))

SLakelandCUMBRIADATA <- read_excel("South LakelandExemptionsLSOA.XLSX", sheet=1)[,1:4] %>%
    StructureData(., lowuse=2:9)

#only inlcudes postcodes so the mergeing needs to be done manually
CopelandCUMBRIADATA <- read_excel("CopelandFOI 5778 data 100517 CBC.XLSX", sheet=1) %>% 
  mutate(Postcode = sub(" ", "", Postcode)) %>%
  left_join(., PstCdLSOA.raw,  by=c("Postcode") ) %>%
  rename(Exemption.type=`Disc Type Ind`, LSOA_CODE = lsoa11cd) %>%
  select(Exemption.type, LSOA_CODE, Postcode, Country_code) %>%
  StructureData()


EdenCUMBRIADATA <- read_excel("EdenDiscountsLSOA.xlsx"  , sheet=1)[1:4] %>%  
  StructureData(.,lowuse = c(2:6,8))

CarliseCUMBRIADATA <- read_excel("FOI 5846 5983-CarlisleDiscountsLSOA June 2017.xlsx"  , sheet=1)[1:4] %>%  
  StructureData(.)

 ls(pattern = "CUMBRIA") %>% map_df(~eval(parse(text=.x))) %>%
  PlotMap(., filter(AG,grepl(paste("Barrow-in-Furness", "Allerdale",
                                    "Carlisle","Copeland","Eden",  
                                    "South Lakeland", sep = "|"), 
                             LAD11NM ) ), 
          filtermap = FALSE,
          title = "Map of Cumbria with all current data")

#Removing Barrow due to the redevelopment only increases the cor slightly
#  ls(pattern = "Cumbria")[-1] %>% map_df(~eval(parse(text=.x)))  %>%
# corplotter(., "MedianPrice", "WardLowUsePerc", 
#            "Median Price vs Low Use % by ward in Cumbria",
#            "Low Use Percentage by Ward",
#            "Median Price")
 
 
 
 ls(pattern = "CUMBRIA") %>% map_df(~eval(parse(text=.x)))  %>%
corplotter(., "MedianPrice", "WardLowUsePerc", 
           "Median Price vs Low Use % by ward in Cumbria",
           "Low Use Percentage by Ward",
           "Median Price")
 
CumbriaStrap <- ls(pattern = "CUMBRIA") %>% map_df(~eval(parse(text=.x))) %>%
   DistribCompareBootstrapper(., 1652, 100)

CumbriaStrap %>%
mutate(RatioExvsAct = (RatioExvsAct-1)*100)%>% 
  ggplot(., aes(x= class, y = RatioExvsAct, fill = class)) + geom_boxplot() + 
  labs(title = "Cumbria", y = "% difference from expected")
SaveFig("CumbriaDistributionPlot.png")

Cumbriattest <- ValueTtest(CumbriaStrap)

z <- ls(pattern = "CUMBRIA") %>% map_df(~eval(parse(text=.x))) %>% MakeLeaflet(.)
z
saveWidget(z, file=file.path(gitpage, "CumbriaLowUse.html"), selfcontained = TRUE )

```

#business rates
```{r}
setwd(file.path(basewd, "Business rates"))
SlakelBuss <- read_csv("sldc-business-rates-full-list-07042017.csv")

test <- SlakelBuss %>% group_by(PropertyDescription) %>% 
  summarise(counts = n())

test2 <- test %>% filter(grepl("SELF", PropertyDescription))

test2$counts %>% sum

SlakelBuss<-SlakelBuss %>% 
  rename(Postcode = PropPostCode) %>%
  mutate(Postcode = gsub(" ", "" , Postcode)) %>%
  filter(grepl("SELF", PropertyDescription)) %>% left_join(., PstCdLSOA.raw, by = "Postcode") %>%
    mutate(LSOA_CODE = lsoa11cd,
         `Exemption type` = "Discount Class B (Furnished & Unocc)") %>%
  select(LSOA_CODE, `Exemption type`)


    test <- SlakelBuss %>% group_by(LSOA_CODE) %>%
    summarise(HomesB = n())

#several hundred un-matchable postcodes
test2 <- SlakelBuss%>% 
  mutate(testme = is.na(lsoa11cd)) %>%
  group_by(AccountName, testme) %>% 
  summarise(count = n()) %>%
  rename

setwd(file.path(RegionsComp, "Region North West"))
SLakelandCUMBRIADATA2 <- read_excel("South LakelandExemptionsLSOA.XLSX", sheet=1)[,1:4] %>%
  bind_rows(SlakelBuss) %>%
    StructureData(., lowuse=2:9)

SLakelandCUMBRIADATA3 <- read_excel("South LakelandExemptionsLSOA.XLSX", sheet=1)[,1:4] %>%
    StructureData2(., lowuse=2:9, Business = SlakelBuss)


MakeLeaflet(SLakelandCUMBRIADATA2)

MakeLeaflet(SLakelandCUMBRIADATA3)

plot(SLakelandCUMBRIADATA$LowUsePerc,SLakelandCUMBRIADATA3$LowUsePerc)


test <- data.frame(Biz =SLakelandCUMBRIADATA3$LowUsePerc, Norm = SLakelandCUMBRIADATA$LowUsePerc ) %>%
  mutate(diff = Biz-Norm)


test %>% ggplot(aes(x= diff)) + geom_density()

```



#Cornwall

```{r}

setwd(file.path(RegionsComp, "Region South West"))

Cornwall <- read_excel("Cornwall.xlsx", sheet=1)%>% setNames(make.names(names(.))) %>% .[,1:4] %>%
  StructureData(lowuse = c(2,23:28))

PlotMap(Cornwall, AG, title = "Lowuse in Cornwall")
SaveFig("Cornwall.png")

# read_excel("Cornwall.xlsx", sheet=1)%>% setNames(make.names(names(.))) %>% .[,1:4] %>%
#   StructureData(lowuse = c(2,7:16, 21:28) ) %>%
#   PlotMap(., AG,title = "all empties")


corplotter(Cornwall, "MedianPrice", "WardLowUsePerc", 
           "Median Price vs Low Use % by ward in Cornwall",
           "Low Use Percentage by Ward",
           "Median Price")
SaveFig("CornCor.png")


Cornstrap <-DistribCompareBootstrapper(Cornwall, 1652, 100)

CornStrap %>%
mutate(RatioExvsAct = (RatioExvsAct-1)*100)%>% 
  ggplot(., aes(x= class, y = RatioExvsAct, fill = class)) + geom_boxplot() + 
  labs(title = "Cornwall", y = "% difference from expected")
SaveFig("CornwallDistributionPlot.png")

Cornttest <- ValueTtest(Cornstrap)

Cornttest$data.frame %>% select(LowUsePrice,HomesPrice) %>%
  gather(key ="type", "meanprice") %>%
  ggplot(., aes(x= type, y = meanprice, fill = type)) + geom_boxplot() 

z <- MakeLeaflet(Cornwall)
z
saveWidget(z, file=file.path(gitpage, "CornwallLowUse.html"), selfcontained = TRUE )


```

Suffolk


```{r}
setwd(file.path(RegionsComp, "Region East of England"))
list.files()

CoastWave <- bind_rows(read.xlsx("FOI IMT178324 SuffolkCoastal.xlsx")[1:4] , read.xlsx("FOI IMT178324 Waveney.xlsx")[1:4]) %>% setNames(make.names(names(.))) %>%
  mutate(Exemption.type = Exemption.type %>% trimws %>%
           make.names %>% 
           gsub("\\.{2,}" , ".", .))  %>%
  StructureData(., lowuse = c(5,6,13,14,16:18))

PlotMap(CoastWave, AG, title ="Low-use Homes in Coastal Suffolk")

corplotter(CoastWave, "MedianPrice", "WardLowUsePerc", 
           "Median Price vs Low Use % by ward in Cumbria",
           "Low Use Percentage by Ward",
           "Median Price")

 SuffStrap<- ls(pattern = "CoastWave") %>% map_df(~eval(parse(text=.x))) %>%
   DistribCompareBootstrapper(., 1652, 1000)

SuffStrap %>%
mutate(RatioExvsAct = (RatioExvsAct-1)*100)%>% 
  ggplot(., aes(x= class, y = RatioExvsAct, fill = class)) + geom_boxplot() + 
  labs(title = "Coastal Suffolk", y = "% difference from expected")
SaveFig("CoastSuffDistributionPlot.png") 

Suffttest <- ValueTtest(SuffStrap)


z <- MakeLeaflet(CoastWave)
z
saveWidget(z, file=file.path(gitpage, "CoastSuffLowUse.html"), selfcontained = TRUE )

```



#Hull
```{r}

Hull <-read_excel(file.path(RegionsComp, "Region Yorkshire and The Humber",
                "KINGSTON UPON HULL%2c CITY OFDISCOUNTSLSOA.XLSX"))[-c(c(1:6)),1:4] %>%
  StructureData(.)

PlotMap(Hull, AG, variable = "WardLowUsePerc")

corplotter(Hull, "MedianPrice", "WardLowUsePerc", 
           "Median Price vs Low Use % by ward in Hull",
           "Low Use Percentage by Ward",
           "Median Price")

 HullStrap<-  DistribCompareBootstrapper(Hull, 1652, 1000)

 HullStrap %>%
mutate(RatioExvsAct = (RatioExvsAct-1)*100) %>% 
  ggplot(., aes(x= class, y = RatioExvsAct, fill = class)) + geom_boxplot() + 
  labs(title = "Cumbria", y = "% difference from expected")
SaveFig("HullDistributionPlot.png")

HullTtest <- ValueTtest(HullStrap)


z <- MakeLeaflet(Hull)
z
saveWidget(z, file=file.path(gitpage, "HullLowUse.html"), selfcontained = TRUE )

```

