---
title: "Untitled"
author: "Jonathan Bourne
date: "29 May 2017"
output: html_document
---


```{r}

library(htmlwidgets)
gitpage <- "/home/jonno/JonnoB.github.io"

```


```{r cars}

points2polygons <- function(df,data) {
  get.grpPoly <- function(group,ID,df) {
         Polygon(coordinates(df[df$id==ID & df$group==group,]))
         }
  get.spPoly  <- function(ID,df) {
         Polygons(lapply(unique(df[df$id==ID,]$group),get.grpPoly,ID,df),ID)
         }
  spPolygons  <- SpatialPolygons(lapply(unique(df$id),get.spPoly,df))
  SpatialPolygonsDataFrame(spPolygons,match.ID=T,data=data)
}

```


```{r}
setwd(gitpage)
z <- MakeLeaflet("chelsea", Chelseainfo)
z
saveWidget(z, file="ChelseaLowUse.html", selfcontained = TRUE )

z<- MakeLeaflet("lambeth", Lambethinfo, c(0:5))
saveWidget(z, file="LambethLowUSe.html", selfcontained = TRUE )


setwd("/home/jonno")
mapshot(z, url = paste0(getwd(), "/map.html"))
```

gSimplify
```{r}
test <- gSimplify(MyData,tol= .0001, topologyPreserve = T) %>% 
  SpatialPolygonsDataFrame(.)

library(geojsonio)
states_json <- geojson_json(MyData,geometry = "polygon")

test <- states_json %>% 
  ms_simplify(keep = 0.005,keep_shapes = TRUE, explode = TRUE) %>% # Simplify polygon
  geojson_sp() 

plot(test)

m2 <- leaflet(test) %>%
    #addTiles()
    addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = v))


bins <- c(0, 10, 20, 25, 100)
pal <- colorBin("YlOrRd", domain = test$LowUsePerc, bins = bins)

labels <- sprintf(
  "<strong>%s</strong><br/>Low-use  %g &#37",
  test$WD16NM, test$LowUsePerc
) %>% lapply(htmltools::HTML)

z2 <-m2 %>% addPolygons(
  fillColor = ~pal(LowUsePerc),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  highlight = highlightOptions(
    weight = 5,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
  label = labels,
  labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto")) %>%
  addLegend(pal = pal, values = ~density, opacity = 0.7, title = NULL,
    position = "bottomright")
saveWidget(z2, file="mapsimple2.html", selfcontained = FALSE )
mapshot(z2, url = paste0(getwd(), "/mapsimple.html"))
```

