---
title: "Untitled"
author: "Jonathan Bourne"
date: "10 August 2017"
output: html_document
---

                                     
                                     
                                     
                                     
                                     
```{r}

CombineLowUse<- function(df){ 
  df %>%
  select(LSOA_CODE, LowUse) %>%
    CalcLowUse()    
    
}                                     



test <- ChelseaLONDATA 


  
test <- ls(pattern = "CUMBRIA") %>% 
  map_df(~get(.x)) %>%
   group_by(LSOA_CODE) %>%
   summarise(LowUse = sum(LowUse, na.rm = TRUE)) %>% 
  CalcLowUse()

z<- MakeLeaflet(test)


testTower <- TowerLONDATA %>%
  CalcLowUse()


test2 <- ls(pattern = "LON") %>%
  map_df(~get(.x)) %>%   
  group_by(LSOA_CODE) %>%
   summarise(LowUse = sum(LowUse, na.rm = TRUE)) %>% 
  CalcLowUse()



test2 <-list( WestminsterLONDATA, ChelseaLONDATA, CoLLONDATA, CamdenLONDATA, TowerLONDATA) %>%
  map_df(~.x) %>%   
  group_by(LSOA_CODE) %>%
   summarise(LowUse = sum(LowUse, na.rm = TRUE)) %>% 
  CalcLowUse()

y<- MakeLeaflet(test2)

y

y2<- MakeLeaflet(TowerLONDATA)

y2

```


https://voaratinglists.blob.core.windows.net/html/rlidata.htm

```{r}

setwd(file.path(basewd,"VOA data"))

file2load <-"uk-englandwales-ndr-2017-summaryvaluations-compiled-epoch-0002-baseline-csv.csv"

test0<- read_lines(file2load, n_max=10)

test <- read_delim(file2load, delim = "*", col_names = F)

test2 <- test$`Offices And Premises` %>% table %>% as.data.frame


g1 <- test %>% filter(X1=="01")
g2 <- test %>% filter(X1=="02")


test3 <- g1$X5 %>% table %>% as.data.frame
test4 <- g2$X4 %>% table %>% as.data.frame

```


```{r}
  file2load2 <- "uk-englandwales-ndr-2017-listentries-compiled-epoch-0002-baseline-csv.csv"
test0<- read_lines(file2load2, n_max=10)

CorePstCd <- PstCdLSOA.raw %>%
  left_join(EW2, by = c("lsoa11cd" = "ECODE")) %>%
  select(Postcode, lsoa11cd, LAD11CD, LAD11NM, Admin_ward_code, WD16NM)

CompanyData <- read_delim(file2load2, delim = "*", col_names = F) %>%
  mutate(X15 = gsub(" ", "", X15)) %>%
  left_join(., CorePstCd, by = c("X15" = "Postcode"))


LSOABiz <- CompanyData %>%
  filter(!is.na(LAD11CD)) %>%
  mutate(X6 = gsub("( AND PREMISES)|( & PREMISES)", "",X6),
         X6 = gsub("(AND PREMISES)|(& PREMISES)", "",X6)) %>%
  group_by(lsoa11cd, X6) %>%
  summarise(counts = n(),
            LAD11CD = first(LAD11CD),
            LAD11NM = first(LAD11NM),
            Admin_ward_code = first(Admin_ward_code),
            WD16NM = first(WD16NM)) 



FirmCounts <- LSOABiz %>%
  group_by(X6) %>%
  summarise(counts = n()) %>%
  arrange(-counts)

Dom <- FirmCounts %>%
  filter(grepl("DOMESTIC",X6))

HOLS <- FirmCounts %>%
  filter(grepl("HOLIDAY",X6))

Catering <- FirmCounts %>%
  filter(grepl("SELF CATER",X6))


```

Look at Westminster

```{r}

West <- LSOABiz %>%
  filter(LAD11CD=="E09000033")


Catering <- West %>%
  filter(grepl("SELF CATER",X6))


test <- list(HammersmithLONDATA, WestminsterLONDATA, ChelseaLONDATA, CoLLONDATA, CamdenLONDATA, LambethLONDATA) %>% 
  map_df(~.x) %>%
  group_by(LAD11CD) %>%
  summarise(
    LAD11NM =first(LAD11NM),
    LowUse = sum(LowUse, na.rm= T),
    Homes = sum(Homes, na.rm= T),
    Pop = sum(Pop, na.rm= T)
            ) %>%
  filter(Homes >2000) %>%
  mutate(LowUseH = LowUse/Homes,
         LowUseP = LowUse/Pop)

```


```{r}

SalesLAD <- prices %>%
  group_by(Admin_district_code) %>%
    filter(X5 %in% c("D", "S", "T", "F")) %>%
    summarise(sales = n(), 
            mean = mean(X2, na.tm = TRUE))
 
SalesWard <- prices %>%
  group_by(Admin_ward_code) %>%
    filter(X5 %in% c("D", "S", "T", "F")) %>%
    summarise(sales = n(), 
            mean = mean(X2, na.tm = TRUE))

SalesWard %>% ggplot(aes(x = sales, y = mean )) + geom_point()
 
```

```{r}
test <- ChelseaLONDATA %>%
            # select(WardLowUsePerc, WardLowUse) %>%
             mutate( WardLowUsePerc = ifelse(is.na(WardLowUsePerc),0, WardLowUsePerc)) %>%
             summarise( maxPerc = max(WardLowUsePerc, na.rm=TRUE),
                        minPerc = min(WardLowUsePerc, na.rm=TRUE),
                        diffPerc = maxPerc-minPerc,
                        max = max(WardLowUse, na.rm=TRUE),
                        min = min(WardLowUse, na.rm=TRUE),
                        diff = max-min,
                        mean = mean(WardLowUse, na.rm=TRUE),
                        median = median(WardLowUse, na.rm=TRUE),
                        LAD = sub("DATA", "", "ChelseaLONDATA"),
                        TurnoverPerc = sum(PercTurnover*Homes, na.rm = TRUE)/sum(Homes, na.rm = TRUE),
                        LUPTurnoverPerc = sum(PercTurnover*LowUse, na.rm = TRUE)/sum(LowUse, na.rm = TRUE)
                        )
```



